name: random_avatar
description: Random Avatar is a multicultural avatar maker. 12 billion unique multicultural avatars
version: 0.0.8
homepage: https://github.com/saytoonz/random_avatar
documentation: https://github.com/saytoonz/random_avatar

environment:
  sdk: ">=2.12.0 <=3.0.1"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
